<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.1" name="trees" tilewidth="16" tileheight="16" tilecount="91" columns="13">
 <image source="trees.png" width="208" height="112"/>
 <tile id="7" type="leaf"/>
 <tile id="14" type="leaf"/>
 <tile id="15" type="leaf"/>
 <tile id="16" type="leaf"/>
 <tile id="19" type="leaf"/>
 <tile id="20" type="leaf"/>
 <tile id="21" type="leaf"/>
 <tile id="26" type="leaf"/>
 <tile id="27" type="leaf"/>
 <tile id="28" type="leaf"/>
 <tile id="29" type="leaf"/>
 <tile id="31" type="leaf"/>
 <tile id="32" type="leaf"/>
 <tile id="33" type="leaf"/>
 <tile id="34" type="leaf"/>
 <tile id="35" type="leaf"/>
 <tile id="37" type="leaf"/>
 <tile id="39" type="leaf"/>
 <tile id="40" type="leaf"/>
 <tile id="41" type="leaf"/>
 <tile id="42" type="leaf"/>
 <tile id="43" type="leaf"/>
 <tile id="44" type="leaf"/>
 <tile id="45" type="leaf"/>
 <tile id="46" type="leaf"/>
 <tile id="47" type="leaf"/>
 <tile id="48" type="leaf"/>
 <tile id="49" type="leaf"/>
 <tile id="50" type="leaf"/>
 <tile id="51" type="leaf"/>
 <tile id="52" type="leaf"/>
 <tile id="53" type="leaf"/>
 <tile id="54" type="leaf"/>
 <tile id="55" type="leaf"/>
 <tile id="56" type="leaf"/>
 <tile id="57" type="leaf"/>
 <tile id="58" type="leaf"/>
 <tile id="59" type="leaf"/>
 <tile id="60" type="leaf"/>
 <tile id="61" type="leaf"/>
 <tile id="62" type="leaf"/>
 <tile id="63" type="leaf"/>
 <tile id="64" type="leaf"/>
 <tile id="66" type="leaf"/>
 <tile id="67" type="leaf"/>
 <tile id="68" type="leaf"/>
 <tile id="70" type="leaf"/>
 <tile id="71" type="leaf"/>
 <tile id="72" type="leaf"/>
 <tile id="73" type="leaf"/>
 <tile id="75" type="leaf"/>
 <tile id="76" type="leaf"/>
 <tile id="77" type="leaf"/>
 <tile id="88" type="leaf"/>
 <tile id="90" type="leaf"/>
</tileset>
